---
title: "Mushroom Thesis Code"
author: "Diana Dima"
output: html_document
---

#loading libraries

library(caret)
library(randomForest)  
library(caTools)  
library(rpart)  
library(rpart.plot)  
library(ggplot2)  
library(readr)
library(corrplot)
library(tidyverse)
library(ROCR)
library(factoextra)

setwd("~/Desktop/final")
mushrooms <- read.csv(file = 'mushrooms.csv')
head(mushrooms)
summary(mushrooms)
str(mushrooms)

#_________________________________________________________________________________________
#EDA 

#Transforming variable observations from character -> factor for bar plots
mushrooms[sapply(mushrooms, is.character)] <- lapply(mushrooms[sapply(mushrooms, is.character)], as.factor) 

#CLASS
ggplot(mushrooms, aes(`class`, fill = `class`)) + geom_bar() + labs(title =
                    "Class Stacked Bar Chart", x = "Class" , y = "Count")+              scale_fill_hue(direction = -1)
                  
#CAP SHAPE
ggplot(mushrooms, aes(`cap.shape`, fill = `class`)) + geom_bar() + labs(title =
                    "Cap Shape Stacked Bar Chart", x = "Cap Shape" , y = "Count") +             scale_fill_hue(direction = -1)

#CAP SURFACE
ggplot(mushrooms, aes(`cap.surface`, fill = `class`)) + geom_bar() + labs(title =
                     "Cap Surface Stacked Bar Chart", x = "Cap Surface" , y = "Count") +             scale_fill_hue(direction = -1)

#CAP COLOR
ggplot(mushrooms, aes(`cap.color`, fill = `class`)) + geom_bar() + labs(title =
                   "Cap Color Stacked Bar Chart", x = "Cap Color" , y = "Count") + 
                   scale_fill_hue(direction = -1)

#BRUISES
ggplot(mushrooms, aes(`bruises`, fill = `class`)) + geom_bar() + labs(title =
                     "Bruises Stacked Bar Chart", x = "Bruises" , y = "Count") +
                     scale_fill_hue(direction = -1)

#ODOR
ggplot(mushrooms, aes(`odor`, fill = `class`)) + geom_bar() + labs(title =
                     "Odor Stacked Bar Chart", x = "Odor" , y = "Count") +
                     scale_fill_hue(direction = -1)
                 
#GILL ATTACHMENT
ggplot(mushrooms, aes(`gill.attachment`, fill = `class`)) + geom_bar() + labs(title =
                     "Gill Attachment Stacked Bar Chart", x = "Gill Attachment" , y = "Count")+
                     scale_fill_hue(direction = -1)


#GILL SPACING
ggplot(mushrooms, aes(`gill.spacing`, fill = `class`)) + geom_bar() + labs(title =
                     "Gill Spacing Stacked Bar Chart", x = "Gill Spacing" , y = "Count") +
                     scale_fill_hue(direction = -1)


#GILL SIZE
ggplot(mushrooms, aes(`gill.size`, fill = `class`)) + geom_bar() + labs(title =
                    "Gill Size Stacked Bar Chart", x = "Gill Size" , y = "Count") +
                     scale_fill_hue(direction = -1)


#GILL COLOR
ggplot(mushrooms, aes(`gill.color`, fill = `class`)) + geom_bar() + labs(title =
                     "Gill Color Stacked Bar Chart", x = "Gill Color" , y = "Count")+
                     scale_fill_hue(direction = -1)


#STALK SHAPE
ggplot(mushrooms, aes(`stalk.shape`, fill = `class`)) + geom_bar() + labs(title =
                    "Stalk Shape Stacked Bar Chart", x = "Stalk Shape" , y = "Count") +
                     scale_fill_hue(direction = -1)


#STALK ROOT
ggplot(mushrooms, aes(`stalk.root`, fill = `class`)) + geom_bar() + labs(title =
                     "Stalk Root Stacked Bar Chart", x = "Stalk Root" , y = "Count")+
                     scale_fill_hue(direction = -1)


#STALK SURFACE ABOVE RING
ggplot(mushrooms, aes(`stalk.surface.above.ring`, fill = `class`)) + geom_bar() + labs(title =
 "Stalk Surface Above Ring Stacked Bar Chart", x = "Stalk Surface Above Ring" , y = "Count")+
                     scale_fill_hue(direction = -1)


#STALK SURFACE BELOW RING 
ggplot(mushrooms, aes(`stalk.surface.below.ring`, fill = `class`)) + geom_bar() + labs(title =
                     "Stalk Surface Below Ring Stacked Bar Chart", x = "Stalk Surface Below Ring" , y = "Count") + scale_fill_hue(direction = -1)


#STALK COLOR ABOVE RING
ggplot(mushrooms, aes(`stalk.color.above.ring`, fill = `class`)) + geom_bar() + labs(title =
                     "Stalk Color Above Ring Stacked Bar Chart", x = "Stalk Color Above Ring" , y = "Count")+ scale_fill_hue(direction = -1)


#STALK COLOR BELOW RING
ggplot(mushrooms, aes(`stalk.color.below.ring`, fill = `class`)) + geom_bar() + labs(title =
                  "Stalk Color Below Ring Stacked Bar Chart", x = "Stalk Color Below Ring" , y = "Count")+ scale_fill_hue(direction = -1)

#VEIL TYPE
ggplot(mushrooms, aes(`veil.type`, fill = `class`)) + geom_bar() + labs(title =
                     "Veil Type Stacked Bar Chart", x = "Veil Type" , y = "Count")+ scale_fill_hue(direction = -1)

#VEIL COLOR
ggplot(mushrooms, aes(`veil.color`, fill = `class`)) + geom_bar() + labs(title =
                     "Veil Color Stacked Bar Chart", x = "Veil Color" , y = "Count")+ scale_fill_hue(direction = -1)


#RING NUMBER
ggplot(mushrooms, aes(`ring.number`, fill = `class`)) + geom_bar() + labs(title =
                    "Ring Number Stacked Bar Chart", x = "Ring Number" , y = "Count")+ scale_fill_hue(direction = -1)


#RING TYPE
ggplot(mushrooms, aes(`ring.type`, fill = `class`)) + geom_bar() + labs(title =
                   "Ring Type Stacked Bar Chart", x = "Ring Type" , y = "Count")+ scale_fill_hue(direction = -1)


#SPORE PRINT COLOR
ggplot(mushrooms, aes(`spore.print.color`, fill = `class`)) + geom_bar() + labs(title =
                   "Spore Print Color Stacked Bar Chart", x = "Spore Print Color" , y = "Count")+ scale_fill_hue(direction = -1)


#POPULATION
ggplot(mushrooms, aes(`population`, fill = `class`)) + geom_bar() + labs(title =                     "Population Stacked Bar Chart", x = "Population" , y = "Count") + scale_fill_hue(direction = -1)

#HABITAT
ggplot(mushrooms, aes(`habitat`, fill = `class`)) + geom_bar() + labs(title =
                     "Habitat Stacked Bar Chart", x = "Habitat" , y = "Count")+ scale_fill_hue(direction = -1)

#_________________________________________________________________________________________

#CORRELATION MATRIX

library(corrplot)
library(RColorBrewer)

#Changing variables from factor to numeric for correlation matrix

mushrooms[sapply(mushrooms, is.factor)] <- lapply(mushrooms[sapply(mushrooms, is.factor)], as.numeric) 
str(mushrooms)

head(mushrooms)

res <- cor(mushrooms)
round(res, 2)

#install.packages("Hmisc")
library(Hmisc)      

res2 <- rcorr(as.matrix(mushrooms))
res2

#Extracting the correlation coefficients

res2$r

#Corrplot

library(corrplot)

table_cor_mushrooms <- cor(mushrooms)     
corrplot(table_cor_mushrooms, method="ellipse")

corrplot(table_cor_mushrooms, method="number")


#_________________________________________________________________________________________

#DATA CLEANING

#Checking  how many variables per class

mushrooms[sapply(mushrooms, is.numeric)] <- lapply(mushrooms[sapply(mushrooms, is.numeric)], as.factor) 
str(mushrooms) 

mushroomClasses<-cbind.data.frame(Var=names(mushrooms), Total_Class=sapply(mushrooms,function(x){as.numeric(length(levels(x)))}))
mushroomClasses


#removing veil type attribute with only one level, and is therefore not deterministic

mushrooms$veil.type <- NULL

#Updating corrplot without veil type attribute

mushrooms[sapply(mushrooms, is.factor)] <- lapply(mushrooms[sapply(mushrooms, is.factor)], as.numeric) 

table_cor_mushrooms <- cor(mushrooms)     
corrplot(table_cor_mushrooms, method="ellipse")


#_________________________________________________________________________________________

#PCA


#scree plot
mushroomsPCA <- prcomp(mushrooms[-1])
fviz_eig(mushroomsPCA, addlabels=T)
options(repr.plot.height=10)

#Loading scores

#PC 1

loadingScores_1 <- mushroomsPCA$rotation[,1]
factorScores_1<- abs(loadingScores_1)
rankedFactorScores_1 <- sort(factorScores_1, decreasing=T)
top10Factors_1 <- names(rankedFactorScores_1[1:10])

mushroomsPCA$rotation[top10Factors_1,1]

#PC 2
loadingScores_2 <- mushroomsPCA$rotation[,2]
factorScores_2<- abs(loadingScores_2)
rankedFactorScores_2 <- sort(factorScores_2, decreasing=T)
top10Factors_2 <- names(rankedFactorScores_2[1:10])

mushroomsPCA$rotation[top10Factors_2,1]

#PC 3
loadingScores_3 <- mushroomsPCA$rotation[,2]
factorScores_3<- abs(loadingScores_3)
rankedFactorScores_3 <- sort(factorScores_3, decreasing=T)
top10Factors_3 <- names(rankedFactorScores_3[1:10])

mushroomsPCA$rotation[top10Factors_3,1]

#PC 4
loadingScores_4 <- mushroomsPCA$rotation[,2]
factorScores_4<- abs(loadingScores_4)
rankedFactorScores_4 <- sort(factorScores_4, decreasing=T)
top10Factors_4 <- names(rankedFactorScores_4[1:10])

mushroomsPCA$rotation[top10Factors_4,1]

#standard deviation
pca.var <- mushroomsPCA$sdev^2
#divide each component by the total variation variation to get a percentage
pca.var.per <- round(pca.var/sum(pca.var)*100,1)

#GRAPHING PCA

var <- get_pca_var(mushroomsPCA)
var

head(var$coord)
head(var$cos2)
head(var$contrib)

# Contributions of variables to PC1
fviz_contrib(mushroomsPCA, choice = "var", axes = 1, top = 10)

# Contributions of variables to PC2
fviz_contrib(mushroomsPCA, choice = "var", axes = 2, top = 10)


#Quality of representation of the variables

corrplot(var$cos2, is.corr=FALSE)

fviz_cos2(mushroomsPCA, choice = "var", axes = 1:2)

#plots show gill color is highly correlated to class


# Color factor map by cos2 values
fviz_pca_var(mushroomsPCA, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE 
             )

#Positively correlated variables = grouped together.
#Negatively correlated variables = on opposite sides of the plot 
#The distance between variables and the origin measures the quality of the variables on the factor map. Variables that are away from the origin are well represented on the factor map.


head(var$contrib, 6)
#cap shape, cap surface, cap color and bruises are top 4


pca.graph <- data.frame(Edible=substring(rownames(mushroomsPCA$class),1,1),
                         X=mushroomsPCA$class[,1],
                         Y=mushroomsPCA$class[,2])
                        
options(repr.plot.height=30, repr.plot.width=30)
fviz_pca_ind(mushroomsPCA, label="none", habillage=mushrooms$class, 
             addEllipses = TRUE, ellipse.level = 0.95, palette = c("green", "red"), repel=TRUE)

             

#FEATURE IMPORTANCE

set.seed(101) 

classRandomFor<- randomForest(class ~ ., data=mushrooms, ntree=1000, keep.forest=FALSE, importance=TRUE)

varImpPlot(classRandomFor, main = "Variable Importance - Mushroom Class")

#Checking Odor relationship with Class 
odor_var <- table(mushrooms$class, mushrooms$odor)
odor_var

#Checking Spore Print Color relationship with Class
sporCol <- table(mushrooms$class, mushrooms$spore.print.color)
sporCol

# Odor is the feature that most affects class, followed by Spore Print Color and Gill Color
#most important variables: odor, gill color, gill size, sportprint color, population, ring type
#least important: gill attachment, cap shape, veil color

str(mushrooms)

mushrooms <- data.frame(lapply(mushrooms, as.factor))

#_________________________________________________________________________________________

#MODELING

#TRAIN, TEST & SPLIT

mushrooms <- data.frame(lapply(mushrooms, as.numeric))

str(mushrooms)

#EDIBLE = 1, POISONOUS = 2

set.seed(202)
p = runif(nrow(mushrooms), 0, 1)
trainLR <- mushrooms [p < 0.7, ]
testLR <- mushrooms [p > 0.7, ]


#_________________________________________________________________________________________

#LOGISTIC MODEL 1 - ALL 21 DEPENDENT VARIABLES

#including all 22 variables
modelLR <- glm(class ~ odor + gill.color + ring.type + habitat + 
              stalk.color.below.ring + spore.print.color + population + 
              gill.size + stalk.root + stalk.surface.above.ring + stalk.color.above.ring + 
              stalk.shape + cap.surface + cap.color + stalk.surface.below.ring +
              ring.number + gill.spacing + cap.shape + bruises + veil.color + gill.attachment, data = trainLR)
summary(modelLR)

#predictions 

predict <- predict(modelLR, type="response")
residuals <- residuals(modelLR)

pred = prediction(predict, trainLR$class)
roc = performance(pred, x.measure = "fpr",measure="tpr")


plot(roc,colorize=TRUE)

#train prediction
classPred <- ifelse(predict < 1.5, 1, 2)
table(actual = trainLR$class, predicted = classPred)

#test prediction
pre <- predict(modelLR, newdata= testLR)
test_pred_class <- ifelse(pre < 1.5 , 1, 2)

table(actual = testLR$class, predicted = test_pred_class)

#EVALUATION METRICS

#Accuracy = TP + TN / TP + TN + FP + FN
#Recall = TP / (TP+FN)
#Precision = TP / (TP+FP)

#ON TRAIN SET

#Accuracy :
(2890 + 2523) / (2890 + 2523 + 189 + 116) # = 0.946
#Recall :
2890 / (2890 + 116) # = 0.961
#Precision :
2890 / (2890 + 189) # = 0.938

#ON TEST SET

#Accuracy : 
(1150 + 1114) / (1150 + 1114 + 90 + 52) # = 0.940
#Recall :
1150 / (1150+52) #= 0.956
#Precision :
1150 / (1150+90) #= 0.927


#________________________
#LOGISTIC MODEL 2 - 6 DEPENDENT VARIABLES

#MODEL LR 2 with 6 variables: ODOR, GILL COLOR, GILL SIZE, SPORE PRINT COLOR, POPULATION & RING TYPE

modelLR_2 <- glm(class ~ odor + gill.color + gill.size + spore.print.color + 
                population + ring.type, data = trainLR)
summary(modelLR_2)

#predictions 

predict_2 <- predict(modelLR_2, type="response")
residuals <- residuals(modelLR_2)

pred_2 = prediction(predict_2, trainLR$class)
roc_2 = performance(pred_2, x.measure = "fpr",measure="tpr")


plot(roc_2,colorize=TRUE)

classPred_2 <- ifelse(predict_2 < 1.5, 1, 2)
table(actual = trainLR$class, predicted = classPred_2)

#Accuracy : 
(2739 + 2432) / (2739 + 2432 + 280 + 267) # = 0.904 - Model1:  = 0.946

#Recall :
2739 / (2739+267) # 0.911 - Model1 : 0.961

#Precision :
2739 / (2739+280) # 0.907 - Model1 : = 0.938

#all model evaluation measures decreased on train set

pre <- predict(modelLR_2, newdata= testLR)
test_pred_class_2 <- ifelse(pre < 1.5 , 1, 2)

table(actual = testLR$class, predicted = test_pred_class_2)

#Accuracy : 
(1085 + 1056) / (1085 + 1056 + 117 + 148) # 0.889 Model1 - 0.940

#Recall :
1085 / (1085+117) # = 0.902 Model1 - 0.956

#Precision :
1085 / (1085 + 148) #0.879 Model1 -  0.927

#all model evaluation measures went down on test set


#________________________
#LOGISTIC MODEL 1 - 3 DEPENDENT VARIABLES


#MODEL LR 3 with 3 variables: ODOR, SPORE PRINT COLOR, GILL COLOR

modelLR_3 <- glm(class ~ odor + gill.color  + spore.print.color, data = trainLR)
summary(modelLR_3)

#predictions 

predict_3 <- predict(modelLR_3, type="response")
residuals <- residuals(modelLR_3)

pred_3 = prediction(predict_3, trainLR$class)
roc_3 = performance(pred_3, x.measure = "fpr",measure="tpr")


plot(roc_3,colorize=TRUE)


classPred_3 <- ifelse(predict_3 < 1.5, 1, 2)
table(actual = trainLR$class, predicted = classPred_3)


pre <- predict(modelLR_3, newdata= testLR)
test_pred_class_3 <- ifelse(pre < 1.5 , 1, 2)

table(actual = testLR$class, predicted = test_pred_class_3)


#all evaluation measures went down again

#________________________
#LOGISTIC MODEL 4 - 18 DEPENDENT VARIABLES

#LR model 4 without gill attachment, cap shape, veil color

modelLR_4 <- glm(class ~ odor + gill.color + ring.type + habitat + 
              stalk.color.below.ring + spore.print.color + population + 
              gill.size + stalk.root + stalk.surface.above.ring + stalk.color.above.ring + 
              stalk.shape + cap.surface + cap.color + stalk.surface.below.ring +
              ring.number + gill.spacing + bruises, data = trainLR)
summary(modelLR_4)


#predictions 

predict_4 <- predict(modelLR_4, type="response")
residuals <- residuals(modelLR_4)

pred_4 = prediction(predict_4, trainLR$class)
roc_4 = performance(pred_4, x.measure = "fpr",measure="tpr")

plot(roc_4,colorize=TRUE)

#train LR4
classPred_4 <- ifelse(predict_4 < 1.5, 1, 2)
table(actual = trainLR$class, predicted = classPred_4)


#test LR4
pre <- predict(modelLR_4, newdata= testLR)
test_pred_class_4 <- ifelse(pre < 1.5 , 1, 2)

table(actual = testLR$class, predicted = test_pred_class_4)

#EVALUATE - TRAIN

#Accuracy :
(2868 + 2528) / (2868 + 2528 + 138 + 184) # 0.943 Model1:  0.946

#Recall :
2868 / (2868 + 138) # = 0.954 Model1: 0.961

#Precision :
2868 / (2868 + 184) # 0.939 Model1:  0.938 SLIGHTLY BETTER

#EVALUATE - TEST

#Accuracy : 
(1140 + 1118) / (1140 + 1118 + 62 + 86 ) # 0.938 Model1:  0.940

#Recall :
1140 / (1140+62) #0.948  Model1  0.956

#Precision :
1140 / (1140+86) #= 0.929 Model1: 0.927 SLIGHTLY BETTER


#________________________
#LOGISTIC MODEL 5 - 19 DEPENDENT VARIABLES

#LR model 5 without gill attachment, veil color

modelLR_5 <- glm(class ~ odor + gill.color + ring.type + habitat + 
              stalk.color.below.ring + spore.print.color + population + 
              gill.size + stalk.root + stalk.surface.above.ring + stalk.color.above.ring + 
              stalk.shape + cap.surface + cap.shape + cap.color + stalk.surface.below.ring +
              ring.number + gill.spacing + bruises, data = trainLR)
summary(modelLR_5)


#predictions 

predict_5 <- predict(modelLR_5, type="response")
residuals <- residuals(modelLR_5)

pred_5 = prediction(predict_5, trainLR$class)
roc_5 = performance(pred_5, x.measure = "fpr",measure="tpr")

plot(roc_5,colorize=TRUE)

#train LR5
classPred_5 <- ifelse(predict_5 < 1.5, 1, 2)
table(actual = trainLR$class, predicted = classPred_5)


#test LR5
pre <- predict(modelLR_5, newdata= testLR)
test_pred_class_5 <- ifelse(pre < 1.5 , 1, 2)

table(actual = testLR$class, predicted = test_pred_class_5)


#results in LR model 4 & 5 the same


#________________________
#LOGISTIC MODEL 6 - 20 DEPENDENT VARIABLES

#LR model 6 without gill attachment

modelLR_6 <- glm(class ~ odor + gill.color + ring.type + habitat + 
              stalk.color.below.ring + spore.print.color + population + 
              gill.size + stalk.root + stalk.surface.above.ring + stalk.color.above.ring + 
              stalk.shape + cap.surface + cap.shape + cap.color + stalk.surface.below.ring +
              ring.number + gill.spacing + bruises + veil.color, data = trainLR)
summary(modelLR_6)


#predictions 

predict_6 <- predict(modelLR_5, type="response")
residuals <- residuals(modelLR_6)

pred_6 = prediction(predict_6, trainLR$class)
roc_6 = performance(pred_6, x.measure = "fpr",measure="tpr")
plot(roc_6,colorize=TRUE)

#train LR6
classPred_6 <- ifelse(predict_5 < 1.5, 1, 2)
table(actual = trainLR$class, predicted = classPred_6)


#test LR6
pre <- predict(modelLR_6, newdata= testLR)
test_pred_class_6 <- ifelse(pre < 1.5 , 1, 2)

table(actual = testLR$class, predicted = test_pred_class_6)


#train

#Accuracy :
(2868 + 2528) / (2868 + 2528 + 138 + 184) # 0.943 Model1 = 0.946

#Recall :
2868 / (2868 + 138) # 0.954 Model1 = 0.961

#Precision :
2868 / (2868 + 184) # 0.939 Model1 = 0.938

#test

#Accuracy : 
(1150 + 1113) / (1150 + 1113 + 91 + 52) # = 0.940 same as Model1

#Recall :
1150 / (1150+52) #= 0.956 same as Model1

#Precision :
1150 / (1150+91) #= 0.927 same as Model1

# conclusion: safe to remove gill attachment and veil color in logistic regression model


#_________________________________________________________________________________________

# RANDOM FOREST 
samplesRF <- mushrooms$class %>% createDataPartition(p=0.7, list=FALSE)

trainRF <- mushrooms[samplesRF, ]
testRF <- mushrooms[-samplesRF, ]

train_modelRF <- trainRF
train_modelRF$class <- replace(train_modelRF$class, train_modelRF$class==1, 'e')
train_modelRF$class <- replace(train_modelRF$class, train_modelRF$class==2, 'p')
head(train_modelRF)

set.seed(42) 
trainRF$class <- as.factor(trainRF$class)
modelRF <- randomForest(class~., 
                             data=trainRF, 
                             ntree=100, 
                             mtry=2, 
                             importance=TRUE,
                             proximity=TRUE)
modelRF

#Random forest predicts a small number of poisonous mushrooms as edible, and no edible mushrooms as poisonous

# FN : actually edible, predicted poisonous - 2
# FP : actually poisonous, predicted edible - 0

#In the case of classifying edible/poisonous mushrooms, FP is more dangerous than FN, and random forest predicts no FP 

#plotting feature importance to see which variables affect prediction the most

#Predicting on test data

rfPred1 <- predict(modelRF,testRF[-1])
table(observed=testRF[,1],predicted=rfPred1)

rfPred2 <- predict(modelRF,testRF[-1],predict.all=TRUE)
table(observed=testRF[,1],predicted=as.factor(rfPred2[2]$individual[,3]))

rfPred3 <- predict(modelRF,testRF[-1],proximity=TRUE)
table(observed=testRF[,1],predicted=rfPred3$pred)


#100 Trees 2 MTRY

#during the second prediction on test data, FP are almost 2x more common than FN
#it is more likely to predict a poisonous mushroom as edible than an edible mushroom as poisonous

#ordered according to how much worse the prediction would be when this feature is removed from model
options(repr.plot.height=10, repr.plot.width=10)
varImpPlot(modelRF)

#Odor, Gill color, stalk root, cap color & spore print color are the top 5 features that affect predictive accuracy

#running RF again with 200 trees

set.seed(101) 
trainRF$class <- as.factor(trainRF$class)
modelRF_2 <- randomForest(class~., 
                             data=trainRF, 
                             ntree=400, 
                             mtry=4, 
                             importance=TRUE,
                             proximity=TRUE)
modelRF_2

#no errors

set.seed(51) 
trainRF$class <- as.factor(trainRF$class)
modelRF_3 <- randomForest(class~., 
                             data=trainRF, 
                             ntree=500, 
                             mtry=2, 
                             importance=TRUE,
                             proximity=TRUE)
modelRF_3

#no FP or FN errors

sample = sample.split(mushrooms$class, SplitRatio = 0.7)

trainMush <- mushrooms[sample, ]
testMush <- mushrooms[-sample, ]

y_train <- trainMush$class
y_test <- testMush$class

set.seed(51) 
trainMush$class <- as.factor(trainMush$class)
modelRF_3 <- randomForest(class~., 
                             data=trainMush, 
                             ntree=500, 
                             mtry=2, 
                             importance=TRUE,
                             proximity=TRUE)
modelRF_3


#Predicting on test data for modelRF_3

rfPred1 <- predict(modelRF_3,testMush[-1])
table(observed=testMush[,1],predicted=rfPred1)

rfPred2 <- predict(modelRF_3,testMush[-1],predict.all=TRUE)
table(observed=testMush[,1],predicted=as.factor(rfPred2[2]$individual[,3]))

rfPred3 <- predict(modelRF_3,testMush[-1],proximity=TRUE)
table(observed=testMush[,1],predicted=rfPred3$pred)


#500 TREES 2 MTRY
#during the second prediction on test data, FN are more common than FP 
#Now, it is more likely to predict an edible mushroom as poisonous than a poisonous mushroom as edible which is less dangerous, however overall there are more errors

#500 trees, 4 MTRY
set.seed(727) 
trainMush$class <- as.factor(trainMush$class)
modelRF_4 <- randomForest(class~., 
                             data=trainMush, 
                             ntree=500, 
                             mtry=4, 
                             importance=TRUE,
                             proximity=TRUE)
modelRF_4

#test 

rfPred1 <- predict(modelRF_4,testMush[-1])
table(observed=testMush[,1],predicted=rfPred1)

rfPred2 <- predict(modelRF_4,testMush[-1],predict.all=TRUE)
table(observed=testMush[,1],predicted=as.factor(rfPred2[2]$individual[,3]))

rfPred3 <- predict(modelRF_4,testMush[-1],proximity=TRUE)
table(observed=testMush[,1],predicted=rfPred3$pred)

#no FP or FN during testing with MTRY 4!

#500 trees, 6 MTRY
set.seed(44) 
trainMush$class <- as.factor(trainMush$class)
modelRF_5 <- randomForest(class~., 
                             data=trainMush, 
                             ntree=500, 
                             mtry=6, 
                             importance=TRUE,
                             proximity=TRUE)
modelRF_5

rfPred1 <- predict(modelRF_5,testMush[-1])
table(observed=testMush[,1],predicted=rfPred1)

rfPred2 <- predict(modelRF_5,testMush[-1],predict.all=TRUE)
table(observed=testMush[,1],predicted=as.factor(rfPred2[2]$individual[,3]))

rfPred3 <- predict(modelRF_5,testMush[-1],proximity=TRUE)
table(observed=testMush[,1],predicted=rfPred3$pred)

# plateau - no further changes in evaluation metrics


#_________________________________________________________________________________________

#DECISION TREE

set.seed(239) 
sample = sample.split(mushrooms$class, SplitRatio = 0.7)

trainMush <- mushrooms[sample, ]
testMush <- mushrooms[-sample, ]

y_train <- trainMush$class
y_test <- testMush$class

trainMush

#install c50 package
library(c50)

modelDT <- C50::C5.0(trainMush[,c(2:22)], as.factor(trainMush$class))
modelDT

summary(modelDT)

C5imp(modelDT)

options(repr.plot.width=10, repr.plot.height=5)
plot(modelDT)

#predictions & testing

library(gmodels)

predDT=predict(modelDT, testMush)
CrossTable(testMush$class, predDT, prop.chisq=FALSE, prop.c=FALSE, prop.r=FALSE, dnn = c('actual class','predicted class'))

#Evaluation metrics
#Accuracy = TP + TN / TP + TN + FP + FN
#Recall = TP / (TP+FN)
#Precision = TP / (TP+FP)

#Accuracy 
(4208 + 3911) / (4208 + 3911 + 4) # = 0.99

#Recall
4208 / 4208 # = 1

#Precision
4208 / (4208 + 4) # = 0.99


test_mushroom=data.frame(
    class=NA,
    cap.shape=NA,
    cap.surface=NA,
    cap.color=NA,
    bruises=NA,
    odor=NA,
    gill.attachment=NA,
    gill.spacing=NA,
    gill.size=NA,
    gill.color=NA,
    stalk.shape=NA,
    stalk.root=NA,
    stalk.surface.above.ring=NA,
    stalk.surface.below.ring=NA,
    stalk.color.above.ring=NA,
    stalk.color.below.ring=NA,
    veil.color=NA,
    ring.number=NA,
    ring.type=NA,
    spore.print.color="b",
    population=NA,
    habitat=NA)

test_mushroom[1,]

pred_test_mushroom_class=predict(modelDT, test_mushroom, type="prob")
pred_test_mushroom_class